### ISSUE TITLE
Compilation errors in workspace on latest IBuild, unable to start IDE in debugger due missing EMF dependencies

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#2121]
I see compilation errors in my workspace on latest IBuild 

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/964108/965b053f-5e6c-4e55-b176-8ed564055748)

and also unable to start IDE in debugger due missing EMF dependencies:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/964108/8f727447-55ff-4ba2-af2a-e0189fd5a186)

_Originally posted by @iloveeclipse in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2118#issuecomment-2162323939_

Most likely regression from https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2118

**Comment by iloveeclipse** [comment]
O, my bad, I had older (not updated) emf.common in my workspace opened. Very sorry.
