### ISSUE TITLE
4.35 I-Build: I20241210-1800 - BUILD FAILED

### ISSUE THREAD

**Issue by SougandhS** [eclipse-platform/eclipse.platform.releng.aggregator#2648]
I20241210-1800 - Failure
see https://ci.eclipse.org/releng/job/Builds/job/I-build-4.35/30/console

<img width="839" alt="image" src="https://github.com/user-attachments/assets/b21066df-ae21-437d-8097-56f44aeac680">

 causing PR - https://github.com/eclipse-equinox/equinox/pull/709

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by jukzi** [comment]
> causing PR - [eclipse-equinox/equinox#709](https://github.com/eclipse-equinox/equinox/pull/709)

@SougandhS can you please elaborate how you know that this PR caused to failure?

**Comment by akurtakov** [comment]
It's enough to look at the build log https://ci.eclipse.org/releng/job/Builds/job/I-build-4.35/30/console

**Comment by jukzi** [comment]
Note that https://ci.eclipse.org/releng/job/equinox/job/master/71/console already shows the error (and many more) but does not fail. Such errors should fail CI builds eager.
```
[2024-12-10T12:00:03.269Z] [INFO] --- javadoc:3.11.2:jar (attach-javadocs) @ org.eclipse.osgi ---
[2024-12-10T12:00:03.525Z] [INFO] No previous run data found, generating javadoc.
[2024-12-10T12:00:13.561Z] [ERROR] MavenReportException: Error while generating Javadoc: 
[2024-12-10T12:00:13.561Z] Exit code: 1
[2024-12-10T12:00:13.561Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/dto/DTO.java:40: error: unknown tag: NotThreadSafe
[2024-12-10T12:00:13.561Z]  * @NotThreadSafe
[2024-12-10T12:00:13.561Z]    ^
[2024-12-10T12:00:13.561Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/framework/BundleActivator.java:48: error: unknown tag: NotThreadSafe
[2024-12-10T12:00:13.561Z]  * @NotThreadSafe
[2024-12-10T12:00:13.561Z]    ^
[2024-12-10T12:00:13.561Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/framework/BundleListener.java:37: error: unknown tag: NotThreadSafe
[2024-12-10T12:00:13.561Z]  * @NotThreadSafe
[2024-12-10T12:00:13.561Z]    ^
[2024-12-10T12:00:13.561Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/framework/FrameworkListener.java:37: error: unknown tag: NotThreadSafe
[2024-12-10T12:00:13.561Z]  * @NotThreadSafe
[2024-12-10T12:00:13.561Z]    ^
[2024-12-10T12:00:13.561Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/framework/dto/BundleDTO.java:29: error: unknown tag: NotThreadSafe
[2024-12-10T12:00:13.561Z]  * @NotThreadSafe
[2024-12-10T12:00:13.561Z]    ^
[2024-12-10T12:00:13.561Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/framework/dto/FrameworkDTO.java:34: error: unknown tag: NotThreadSafe
[2024-12-10T12:00:13.561Z]  * @NotThreadSafe
[2024-12-10T12:00:13.561Z]    ^
[2024-12-10T12:00:13.561Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/framework/dto/ServiceReferenceDTO.java:37: error: unknown tag: NotThreadSafe
[2024-12-10T12:00:13.561Z]  * @NotThreadSafe
[2024-12-10T12:00:13.561Z]    ^
[2024-12-10T12:00:13.561Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/framework/hooks/resolver/ResolverHook.java:132: error: unknown tag: NotThreadSafe
[2024-12-10T12:00:13.561Z]  * @NotThreadSafe
[2024-12-10T12:00:13.561Z]    ^
[2024-12-10T12:00:13.561Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/framework/hooks/weaving/WovenClass.java:36: error: unknown tag: NotThreadSafe
[2024-12-10T12:00:13.561Z]  * @NotThreadSafe
[2024-12-10T12:00:13.561Z]    ^
[2024-12-10T12:00:13.562Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/framework/startlevel/dto/BundleStartLevelDTO.java:30: error: unknown tag: NotThreadSafe
[2024-12-10T12:00:13.562Z]  * @NotThreadSafe
[2024-12-10T12:00:13.562Z]    ^
[2024-12-10T12:00:13.562Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/framework/startlevel/dto/FrameworkStartLevelDTO.java:30: error: unknown tag: NotThreadSafe
[2024-12-10T12:00:13.562Z]  * @NotThreadSafe
[2024-12-10T12:00:13.562Z]    ^
[2024-12-10T12:00:13.562Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/framework/wiring/dto/BundleRevisionDTO.java:32: error: unknown tag: NotThreadSafe
[2024-12-10T12:00:13.562Z]  * @NotThreadSafe
[2024-12-10T12:00:13.562Z]    ^
[2024-12-10T12:00:13.562Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/resource/dto/ResourceDTO.java:27: error: unknown tag: NotThreadSafe
[2024-12-10T12:00:13.562Z]  * @NotThreadSafe
[2024-12-10T12:00:13.562Z]    ^
[2024-12-10T12:00:13.562Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/framework/wiring/dto/BundleWireDTO.java:30: error: unknown tag: NotThreadSafe
[2024-12-10T12:00:13.562Z]  * @NotThreadSafe
[2024-12-10T12:00:13.562Z]    ^
[2024-12-10T12:00:13.562Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/resource/dto/WireDTO.java:26: error: unknown tag: NotThreadSafe
[2024-12-10T12:00:13.562Z]  * @NotThreadSafe
[2024-12-10T12:00:13.562Z]    ^
[2024-12-10T12:00:13.562Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/framework/wiring/dto/BundleWiringDTO.java:34: error: unknown tag: NotThreadSafe
[2024-12-10T12:00:13.562Z]  * @NotThreadSafe
[2024-12-10T12:00:13.562Z]    ^
[2024-12-10T12:00:13.562Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/framework/wiring/dto/BundleWiringDTO.java:77: error: unknown tag: NotThreadSafe
[2024-12-10T12:00:13.562Z]      * @NotThreadSafe
[2024-12-10T12:00:13.562Z]        ^
[2024-12-10T12:00:13.562Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/resource/dto/WiringDTO.java:27: error: unknown tag: NotThreadSafe
[2024-12-10T12:00:13.562Z]  * @NotThreadSafe
[2024-12-10T12:00:13.562Z]    ^
[2024-12-10T12:00:13.562Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/framework/wiring/dto/FrameworkWiringDTO.java:30: error: unknown tag: NotThreadSafe
[2024-12-10T12:00:13.562Z]  * @NotThreadSafe
[2024-12-10T12:00:13.562Z]    ^
[2024-12-10T12:00:13.562Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/resource/dto/CapabilityDTO.java:27: error: unknown tag: NotThreadSafe
[2024-12-10T12:00:13.562Z]  * @NotThreadSafe
[2024-12-10T12:00:13.562Z]    ^
[2024-12-10T12:00:13.562Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/resource/dto/CapabilityRefDTO.java:25: error: unknown tag: NotThreadSafe
[2024-12-10T12:00:13.562Z]  * @NotThreadSafe
[2024-12-10T12:00:13.562Z]    ^
[2024-12-10T12:00:13.562Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/resource/dto/RequirementDTO.java:27: error: unknown tag: NotThreadSafe
[2024-12-10T12:00:13.562Z]  * @NotThreadSafe
[2024-12-10T12:00:13.562Z]    ^
[2024-12-10T12:00:13.562Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/resource/dto/RequirementRefDTO.java:25: error: unknown tag: NotThreadSafe
[2024-12-10T12:00:13.562Z]  * @NotThreadSafe
[2024-12-10T12:00:13.562Z]    ^
[2024-12-10T12:00:13.562Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/service/log/LogListener.java:33: error: reference not found
[2024-12-10T12:00:13.562Z]  * Since 1.4, {@link org.osgi.service.log.stream.LogStreamProvider} is the
[2024-12-10T12:00:13.562Z]                      ^
[2024-12-10T12:00:13.562Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/service/log/LogReaderService.java:26: error: reference not found
[2024-12-10T12:00:13.562Z]  * Since 1.4, {@link org.osgi.service.log.stream.LogStreamProvider} is the
[2024-12-10T12:00:13.562Z]                      ^
[2024-12-10T12:00:13.562Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/internal/framework/FilterImpl.java:115: error: attribute "border" for table only accepts "" or "1": BORDER
[2024-12-10T12:00:13.562Z]  * <TABLE BORDER=0>
[2024-12-10T12:00:13.562Z]           ^
[2024-12-10T12:00:13.562Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/internal/framework/FilterImpl.java:124: error: attribute not supported in HTML5: valign
[2024-12-10T12:00:13.562Z]  * <TR valign=top>
[2024-12-10T12:00:13.563Z]        ^
[2024-12-10T12:00:13.563Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/internal/hookregistry/StorageHookFactory.java:36: warning: empty <p> tag
[2024-12-10T12:00:13.563Z]  * <p>
[2024-12-10T12:00:13.563Z]    ^
[2024-12-10T12:00:13.563Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/framework/AdaptPermission.java:281: warning: empty <p> tag
[2024-12-10T12:00:13.563Z] 	 * <p>
[2024-12-10T12:00:13.563Z] 	   ^
[2024-12-10T12:00:13.563Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/internal/url/MultiplexingFactory.java:44: error: unknown tag: AccessibleObject
[2024-12-10T12:00:13.563Z] 	 * Collection<AccessibleObject> simply to provide a method add(AccessibleObject)
[2024-12-10T12:00:13.563Z] 	             ^
[2024-12-10T12:00:13.563Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/internal/framework/EquinoxEventPublisher.java:345: error: unknown tag: BundleContextImpl
[2024-12-10T12:00:13.563Z] 	 * Coerce the generic type of a collection from Collection<BundleContextImpl> to
[2024-12-10T12:00:13.563Z] 	                                                          ^
[2024-12-10T12:00:13.563Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/internal/framework/EquinoxEventPublisher.java:346: error: unknown tag: BundleContext
[2024-12-10T12:00:13.563Z] 	 * Collection<BundleContext>
[2024-12-10T12:00:13.563Z] 	             ^
[2024-12-10T12:00:13.563Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/internal/framework/EquinoxEventPublisher.java:349: error: unknown tag: BundleContext
[2024-12-10T12:00:13.563Z] 	 * @return c coerced to Collection<BundleContext>
[2024-12-10T12:00:13.563Z] 	                                  ^
[2024-12-10T12:00:13.563Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/service/log/LogReaderService.java:59: error: reference not found
[2024-12-10T12:00:13.563Z] 	 * Since 1.4, {@link org.osgi.service.log.stream.LogStreamProvider} is the
[2024-12-10T12:00:13.563Z] 	                     ^
[2024-12-10T12:00:13.563Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/osgi/src/org/osgi/service/log/LogReaderService.java:77: error: reference not found
[2024-12-10T12:00:13.563Z] 	 * Since 1.4, {@link org.osgi.service.log.stream.LogStreamProvider} is the
[2024-12-10T12:00:13.563Z] 	                     ^
[2024-12-10T12:00:13.563Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/internal/debug/FrameworkDebugOptions.java:70: error: malformed HTML
[2024-12-10T12:00:13.563Z] 	 * <key,value> --> <bundle name, DebugTrace>
[2024-12-10T12:00:13.563Z] 	   ^
[2024-12-10T12:00:13.563Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/internal/debug/FrameworkDebugOptions.java:70: error: malformed HTML
[2024-12-10T12:00:13.563Z] 	 * <key,value> --> <bundle name, DebugTrace>
[2024-12-10T12:00:13.563Z] 	                   ^
[2024-12-10T12:00:13.563Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/internal/hookregistry/HookRegistry.java:124: warning: empty <p> tag
[2024-12-10T12:00:13.563Z] 	 * <p>
[2024-12-10T12:00:13.563Z] 	   ^
[2024-12-10T12:00:13.563Z] /home/jenkins/agent/workspace/equinox_master/equinox/bundles/org.eclipse.osgi/supplement/src/org/eclipse/osgi/util/NLS.java:151: error: unexpected end tag: </p>
[2024-12-10T12:00:13.563Z] 	 * </p>
[2024-12-10T12:00:13.563Z] 	   ^
[2024-12-10T12:00:13.563Z] 36 errors
[2024-12-10T12:00:13.563Z] 3 warnings
[2024-12-10T12:00:13.563Z] Command line was: /opt/tools/java/temurin/jdk-17/jdk-17.0.13+11/bin/javadoc -J-Duser.language= -J-Duser.country= @options @packages
```

**Comment by laeubi** [comment]
> Note that https://ci.eclipse.org/releng/job/equinox/job/master/71/console already shows the error (and many more) but does not fail. Such errors should fail CI builds eager.

Everyone is encouraged to helf fixing als javadoc problems and then we can enable the failure check... in the past this was just claimed to be too restrictive/much efforts ...

**Comment by akurtakov** [comment]
I have started the effort in https://github.com/eclipse-equinox/equinox/pull/716

**Comment by merks** [comment]
I felt encourage to fix the problem.  👼

**Comment by merks** [comment]
Indeed, it would be better to fail the PR than to have the I-build fail later.

**Comment by SougandhS** [comment]
> @SougandhS can you please elaborate how you know that this PR caused to failure?

went through the build logs https://ci.eclipse.org/releng/job/Builds/job/I-build-4.35/30/console and saw the stack trace -> equinox/bundles/org.eclipse.osgi/supplement/src/org/eclipse/osgi/util/NLS.java:151: error: unexpected end tag: </p> and then found the PR made that change.

**Comment by merks** [comment]
I think this is fixed now and I started:

https://ci.eclipse.org/releng/job/Builds/job/I-build-4.35/31/

**Comment by SougandhS** [comment]
Thank you @merks

**Comment by jukzi** [comment]
> and I started:

something went wrong with the windows build, feels like it did not test every bundle:
![image](https://github.com/user-attachments/assets/89e054b2-cbad-454d-869b-e74040738532)

**Comment by HeikoKlare** [comment]
The Windows build errored because some cleanup of Edge browser artifacts (lockfile) failed:
> C:\Users\genie.releng\workspace\AutomatedTests\ep435I-unit-win32-x86_64-java17\workarea\I20241211-0310\eclipse-testing\test.xml:132: Unable to delete file C:\Users\genie.releng\workspace\AutomatedTests\ep435I-unit-win32-x86_64-java17\workarea\I20241211-0310\eclipse-testing\test-eclipse\eclipse\update_configurator_folder.metadata.plugins\org.eclipse.swt\EBWebView\lockfile

So I expect this to be caused by merging https://github.com/eclipse-platform/eclipse.platform.swt/pull/1637 to use Edge as default browser. Not sure whether that's something indeterministic: I just pinged colleagues to check the error in the according PR (https://github.com/eclipse-platform/eclipse.platform.swt/pull/1637#issuecomment-2536858234).
